### PR TITLE
chore: bump diagram-js

### PR DESCRIPTION
**Pull request by boris-petrov**
cc @pinussilvestrus

### CODE REVIEW

**Comment by marstamm** [comment]
Seems like package-lock is not updated in this one?

**Comment by boris-petrov** [comment]
@marstamm well, there is no `package-lock.json` in this repo. :smile:

**Comment by marstamm** [comment]
Oh shoot, my bad. Feel free to create one then 😅

**Comment by boris-petrov** [comment]
Unfortunately I'll create it with a lockfile version 2, so it's perhaps better if you do it. :)

**Comment by marstamm** [comment]
Will do 👍

**Comment by boris-petrov** [comment]
You can also remove `karma-phantomjs-launcher` from `package.json` now that you've migrated to using Chrome.

**Comment by marstamm** [comment]
I've removed the unused launchers 👍

**Comment by marstamm** [comment]
Was phantomJS even working for you? It was broken for me when I tried it, even on master

**Comment by boris-petrov** [comment]
Nope, wasn't working. I thought the problem was with my setup. :)

**Comment by marstamm** [comment]
I'll release these right away 🙂

**Comment by boris-petrov** [comment]
Great! Thank you for the awesome support!

**Pull request merged**
